version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./main:/main
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build: .
    volumes:
      - ./main:/main
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: web
    ports:
      - "6603:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: